# Generated by Django 4.2.25 on 2025-10-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(help_text='Duración del servicio. Formato: HH:MM:SS.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_type', models.CharField(choices=[('LOCAL', 'En el local'), ('DOMICILIO', 'A domicilio'), ('AMBOS', 'Ambos (a elegir por el cliente)')], default='LOCAL', help_text='Define dónde se puede realizar este servicio específico.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
