# Generated by Django 4.2.25 on 2025-10-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Personal asignado para realizar este servicio.', related_name='services_offered', to='users.staffmember'),
        ),
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.business'),
        ),
    ]
