# Generated by Django 4.2.25 on 2025-10-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_type',
            field=models.CharField(choices=[('LOCAL', 'En el local'), ('DOMICILIO', 'A domicilio'), ('AMBOS', 'Ambos (a elegir por el cliente)')], default='LOCAL', help_text='Define dónde se puede realizar este servicio específico.', max_length=10),
        ),
    ]
