# Generated by Django 4.2.25 on 2025-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio (opcional).', null=True, upload_to='services/photos/'),
        ),
    ]
