# Generated by Django 4.2.25 on 2025-10-08 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_delivery_type',
            field=models.CharField(choices=[('LOCAL', 'Solo atiende en su local'), ('DOMICILIO', 'Solo atiende a domicilio'), ('AMBOS', 'Ofrece ambos servicios')], default='LOCAL', help_text='Define el modelo de atención general del profesional.', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='travel_buffer',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Tiempo extra que se bloqueará ANTES y DESPUÉS de cada servicio a domicilio para traslados.'),
        ),
    ]
