# Generated by Django 4.2.25 on 2025-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#3498DB', help_text='Color principal del tema (formato hex, ej: #FF0000)', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Color secundario del tema (formato hex, ej: #00FF00)', max_length=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, help_text='Dirección del cliente para servicios a domicilio.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS (Latitud) para domicilio.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS (Longitud) para domicilio.', max_digits=10, null=True),
        ),
    ]
