# Generated by Django 4.2.25 on 2025-10-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_primary_color_business_secondary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del plan (Ej: Básico, Profesional)', max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Precio mensual', max_digits=6)),
                ('max_staff', models.IntegerField(default=1, help_text='Número máximo de miembros de personal permitidos (-1 para ilimitado)')),
                ('allow_payments', models.BooleanField(default=False, help_text='Permite aceptar pagos online')),
                ('allow_whatsapp_reminders', models.BooleanField(default=False)),
                ('allow_custom_branding', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este plan se puede asignar a nuevos clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'En Prueba'), ('ACTIVE', 'Activo'), ('PAST_DUE', 'Pago Vencido'), ('INACTIVE', 'Inactivo'), ('CANCELED', 'Cancelado'), ('DEMO', 'Demostración')], default='TRIAL', max_length=10)),
                ('trial_end_date', models.DateField(blank=True, help_text='Fecha en que termina el periodo de prueba', null=True)),
                ('current_period_end', models.DateField(blank=True, help_text='Fecha en que termina el periodo pagado actual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.plan')),
            ],
        ),
    ]
