# Generated by Django 4.2.25 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='users/profile_pics/'),
        ),
    ]
