# Generated by Django 4.2.25 on 2025-10-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la zona (Ej: Guayaquil Centro, 090101, Samborondón)', max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='service_zones',
            field=models.ManyToManyField(blank=True, help_text='Zonas geográficas cubiertas para servicios a domicilio (basado en nombres/códigos).', related_name='businesses', to='users.servicezone'),
        ),
    ]
