# Generated by Django 4.2.25 on 2025-10-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_servicezone_business_service_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad donde opera el negocio.', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, default='Ecuador', help_text='País donde opera el negocio.', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección detallada (Calle, número, etc.).', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL (generado automáticamente).', max_length=100, unique=True),
        ),
    ]
