# Generated by Django 4.2.25 on 2025-10-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_business_city_business_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario.', max_length=20),
        ),
    ]
