# Generated by Django 4.2.25 on 2025-11-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('user', 'business')},
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas sobre este cliente (visto solo por el negocio).'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, help_text='Dirección del cliente para este negocio (domicilios).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
