"""
Django settings for tivy project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# Leemos la SECRET_KEY desde el archivo .env
#SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Leemos el valor de DEBUG. El cast=bool lo convierte a True/False
#DEBUG = config('DEBUG', default=False, cast=bool)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-19r)=5n!v-)gd0=)e(jjzjp929x92x*uu9x+la62v6rm@#d9za'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '*'
    #'4f107676df1b.ngrok-free.app', # <-- Añade esta línea
]

#ALLOWED_HOSTS = ['*','4f107676df1b.ngrok-free.app', 'localhost']
# Ajustes de Cookies para Desarrollo Local
# FORZAR COMPATIBILIDAD LOCAL
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_DOMAIN = None  # Deja que el navegador decida el dominio

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'https://4f107676df1b.ngrok-free.app',
]
#CSRF_TRUSTED_ORIGINS = [
#    'https://4f107676df1b.ngrok-free.app ' # <-- Asegurate de incluir https://
#]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'CoreApps.users',
    'CoreApps.catalog',
    'CoreApps.scheduling',
    'CoreApps.loyalty',
    'CoreApps.payments',
    'CoreApps.main',
    # DRF
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tivy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tivy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#DATABASES = {
#    'default': {
#        'ENGINE': config('DB_ENGINE'),
#        'NAME': config('DB_NAME'),
#        'USER': config('DB_USER'),
#        'PASSWORD': config('DB_PASSWORD'),
#        'HOST': config('DB_HOST'),
#        'PORT': config('DB_PORT'),
#    }
#}

AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL pública que se usará para acceder a los archivos multimedia en el navegador.
# Debe terminar en barra '/'.
MEDIA_URL = '/media/'

# Ruta absoluta en tu disco duro donde se guardarán los archivos subidos.
# BASE_DIR apunta a la raíz de tu proyecto.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# --- AGREGÁ ESTA LÍNEA ---
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# Al final de settings.py
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'


# WASenderAPI Configuration
WASENDERAPI_API_KEY = os.getenv('WASENDERAPI_API_KEY')
WASENDERAPI_BASE_URL = os.getenv('WASENDERAPI_BASE_URL')
print(f"WASenderAPI Key loaded: {WASENDERAPI_API_KEY is not None and len(WASENDERAPI_API_KEY) > 0}")
print(f"WASenderAPI Base URL loaded: {WASENDERAPI_BASE_URL}")
