# Generated by Django 4.2.25 on 2025-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10)),
                ('provider', models.CharField(default='payphone', max_length=50)),
                ('provider_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
