# Generated by Django 4.2.25 on 2025-10-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='users.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.service'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityrule',
            unique_together={('client', 'day_of_week')},
        ),
    ]
