# Generated by Django 4.2.25 on 2025-10-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_service_delivery_type_client_travel_buffer'),
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='users.client')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailabilityRule',
        ),
    ]
