# Generated by Django 4.2.25 on 2025-10-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, help_text='Motivo del bloqueo (opcional)', max_length=150, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='availabilityblock',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='staff_can_edit',
            field=models.BooleanField(default=True, help_text='Permite que el miembro del staff (si tiene login) modifique o elimine este bloque.'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='availability_start_before_end'),
        ),
        migrations.AddField(
            model_name='timeoffblock',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_blocks', to='users.staffmember'),
        ),
        migrations.AddConstraint(
            model_name='timeoffblock',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='timeoff_start_before_end'),
        ),
    ]
